### ISSUE TITLE
Offset and ordering not following column naming convention

### ISSUE THREAD

**Issue by jlafitte** [leejordan/reflex#54] opened 2018-04-25 14:58 UTC
So the column naming convention is:
`.col-<breakpoint>-<n>`

But the order and offset are:
`.order-<n>-<breakpoint>`
`.offset-<n>-<breakpoint>`

This creates confusion for us.  We think they should be:
`.order-<breakpoint>-<n>`
`.offset-<breakpoint>-<n>`

I was just going to "fix" it in my fork, but then your nice documentation would no longer apply.  What do you think about this issue?  Any chance you may reconsider the naming for these?

**Comment by marcorieser** [comment] 2018-04-25 15:30
Seems like i mixed up something with my pull request bringing in this feature. Why don't you fix the docs too and make a pull request?

**Comment by jlafitte** [comment] 2018-04-26 19:23
I wouldn't blame you as it looks like you were following the convention for order, but it seems to make sense that there is a global common naming convention.  SASS isn't really my specialty (my fork is a LESS version of it) but I will try to fix it and do a pull request when I can make some time.

**Comment by marcorieser** [comment] 2018-04-27 06:19
@jlafitte i pushed the fix as a pull request.

**Comment by leejordan** [comment] 2018-05-23 07:11
I think this is a fair comment. I will look to merge marcorieser's pull request. The problem is that now I am used to using the classes in this way so although your suggested change is good for consistency it means I'll have to get used to the new syntax :)

**Comment by leejordan** [comment] 2018-06-26 22:41
I still plan to merge this, I just need to find some time to look at it properly.

**Comment by sntran** [comment] 2018-10-11 19:48
@leejordan Did you have a chance to look at this minor change? Consistency is good.

**Comment by leejordan** [comment] 2018-12-11 16:03
It's merged and in the latest release 2.0.4

Thanks!

**Closed as completed by leejordan** 2018-12-11 16:03 UTC
